name: Webpack Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Build
      run: |
        npm install
        NODE_ENV=production NODE_OPTIONS=--loader=ts-node/esm webpack --mode production
        git config advice.addIgnoredFile false
        rm -r allowlist.json webpack.config.ts server.properties README.md permissions.json package.json package-lock.json .gitignore .deepsource.toml scripts client log dns .github tsconfig.json upgrade.txt
        git config --global user.email "wolfemikl@gmail.com"
        git config --global user.name "Mikl Wolfe"
        git add docs
        git commit -am 'Update production build'
        git push -f origin main:client
